- src-tauri/src/lang.rs
- src-tauri/src/main.rs
- src-tauri/src/proxy.rs
- src-tauri/src/system_helpers.rs
This fixes the program crashing on startup on Windows, and also the language files not loading on Windows.
> Fix Windows path issues

- src-tauri/lang/cht.json
> Traditional Chinese | Translation Patches

- src-tauri/lang/cht.json
> minor edits cause i fucked up again

- src-tauri/lang/de.json
Translated the "en.json" into german
> Added german language file

- THEMES.md
- docs/elementIds.md
- src/ui/App.tsx
- src/ui/components/MiniDialog.tsx
- src/ui/components/RightBar.tsx
- src/ui/components/ServerLaunchSection.tsx
- src/ui/components/TopBar.tsx
- src/ui/components/common/BigButton.tsx
- src/ui/components/common/Checkbox.tsx
- src/ui/components/common/DirInput.tsx
- src/ui/components/common/DownloadSection.tsx
- src/ui/components/common/HelpButton.tsx
- src/ui/components/common/MainProgressBar.tsx
- src/ui/components/common/ProgressBar.tsx
- src/ui/components/common/TextInput.tsx
- src/ui/components/menu/Divider.tsx
- src/ui/components/menu/Downloads.tsx
- src/ui/components/menu/Menu.tsx
- src/ui/components/menu/Options.tsx
- src/ui/components/news/NewsSection.tsx
- yarn.lock
yes i sat here and did the boring job of documenting actually real
> Add element id's and their documentation

- src-tauri/lang/ru.json
translated en.json into russian
> Added russian language file

- src-tauri/lang/fr.json
I translated Cultivation to french. It's really the only way i can be useful for this project
> French language file

- src-tauri/lang/lv.json
translated cultivation to latvian language
> Added latvian language file

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/proxy.rs
- src-tauri/src/system_helpers.rs
- src/utils/configuration.ts
This gets the launcher building and running on Linux (and Mac, though I haven't tested it). There are still some more things to fix, not including implementing the actual proxying which I won't implement in this PR.
> Fix build errors on Unix

- src-tauri/lang/chs.json
> Chinese Simplified Translations Update

- src-tauri/lang/chs.json
> Updated Simplified Chinese translations

- src-tauri/lang/ko.json
This is a file provided by @koreako12 in #128 for Korean translation.
Resolves #128
> Add Korean Translation by @koreako12

- src-tauri/lang/chs.json
- src-tauri/lang/cht.json
- src-tauri/lang/de.json
- src-tauri/lang/en.json
- src-tauri/lang/es.json
- src-tauri/lang/fr.json
- src-tauri/lang/id.json
- src-tauri/lang/ko.json
- src-tauri/lang/lv.json
- src-tauri/lang/nl.json
- src-tauri/lang/pt-br.json
- src-tauri/lang/ru.json
- src-tauri/lang/vi.json
- src-tauri/src/main.rs
- src-tauri/src/proxy.rs
- src-tauri/src/system_helpers.rs
- src/ui/components/ServerLaunchSection.tsx
- src/ui/components/menu/Options.tsx
- src/utils/configuration.ts
- src/utils/download.ts
- src/utils/rsa.ts
- Adds setting to run the game in a non-elevated state
- Fixes mods appearing stuck extracting when downloading several
- Fixes downloads menu buttons appearing stuck after clicking them
- Fixes old rsa patch being used when it was backed up
- Automatically removes spaces from the address bar, which should prevent invalid uri characters in most cases
> Non-elevated option & bugfix

- src-tauri/src/main.rs
- src-tauri/src/patch.rs
- src-tauri/src/release.rs
- src-tauri/src/system_helpers.rs
- src-tauri/src/web.rs
- src-tauri/tauri.conf.json
- src/ui/Mods.css
- src/ui/Mods.tsx
- src/ui/components/mods/ModList.tsx
- src/ui/components/mods/ModPages.css
- src/ui/components/mods/ModPages.tsx
- src/ui/components/news/NewsSection.tsx
- src/utils/gamebanana.ts
Improves mod browser loading times and ease of use
- 50 mods per page for loading time improvement (previously was every mod on one page)
- Pages & searching added
- Reuse a single reqwest client for performance
- Linting & formatting
- Bump version
> Improve Mod Browser

- src-tauri/src/gamebanana.rs
- src-tauri/src/main.rs
- src-tauri/src/system_helpers.rs
- src/ui/components/mods/ModList.tsx
- src/utils/gamebanana.ts
- Improve mod search using actual API
- Fix the fix of unix building
> Improved search

- src/ui/components/ServerLaunchSection.tsx
Fixes help button not properly showing help text for port.
Fixes #159
> Fix port help box

- src-tauri/src/main.rs
- src-tauri/src/unzip.rs
- src/ui/Main.tsx
Uncomment reopen as admin
Re-add set migoto exe when downloading from menu
> Re-open as admin

- src/ui/Main.tsx
- src/ui/components/menu/GamePathNotify.css
- src/ui/components/menu/GamePathNotify.tsx
Whenever the game path is not set, a notification shows up that reminds you to do that. Hopefully there won't be conflicts anymore.
> Final pull request for set game path notification

- src/ui/components/menu/Downloads.tsx
Changes individual resources download link to api for dynamic updating.
> Update resources link

- src/ui/components/menu/Downloads.tsx
Remove unstable download
Add back questing aio
> Fix downloads menu

- src-tauri/lang/it.json
> Add italian language support

- src-tauri/lang/pl.json
The translation is based on `en.json`.
> Add Polish translation

- src-tauri/src/config.rs
- src/ui/components/ServerLaunchSection.tsx
Fixes launch args not being properly applied when set in the settings menu.
> Fix args in settings

- README.md
- README_ja-JP.md
- README_zh-CN.md
- README_zh-TW.md
- src-tauri/lang/ja.json
> Add Japanese language support
